// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://decslzcfkjthdutnvorz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlY3NsemNma2p0aGR1dG52b3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzgwOTksImV4cCI6MjA3NDM1NDA5OX0.D6crm_brL99uBBkc4uSj_Uzl4RsNlAVWXRnS2eYD-tE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});